version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
